In [4]:
from csv import reader
import numpy as np

In [2]:
with open('heart-disease.csv', 'r', encoding='UTF-8') as file:
    data = reader(file)
    data = list(data)

In [7]:
data = np.array(data)

In [8]:
data

array([['\ufeffage', 'sex', 'cp', ..., 'ca', 'thal', 'target'],
       ['63', '1', '3', ..., '0', '1', '1'],
       ['37', '1', '2', ..., '0', '2', '1'],
       ...,
       ['68', '1', '0', ..., '2', '3', '0'],
       ['57', '1', '0', ..., '1', '3', '0'],
       ['57', '0', '1', ..., '1', '2', '0']], dtype='<U8')

In [17]:
header = data[0]
np_data = data[1:,:].astype('float')
np_data

array([[63.,  1.,  3., ...,  0.,  1.,  1.],
       [37.,  1.,  2., ...,  0.,  2.,  1.],
       [41.,  0.,  1., ...,  0.,  2.,  1.],
       ...,
       [68.,  1.,  0., ...,  2.,  3.,  0.],
       [57.,  1.,  0., ...,  1.,  3.,  0.],
       [57.,  0.,  1., ...,  1.,  2.,  0.]])

In [18]:
type(np_data)

numpy.ndarray

In [23]:
np_data.argmax(axis=0)

array([238,   0,   0, 223,  85,   0, 144,  72,   4, 204,   2,  92,   7,
         0])

In [24]:
np_data.dtype

dtype('float64')

In [32]:
age_val = np_data[:,0]

In [36]:
lt30gt20 = np_data[(age_val<30)&(age_val>20)]

In [38]:
unique_numbers, counts = np.unique(lt30gt20,return_counts=True)

In [39]:
unique_numbers,counts

(array([  0.,   1.,   2.,  29., 130., 202., 204.]),
 array([5, 3, 2, 1, 1, 1, 1]))

In [42]:
np.random.shuffle(unique_numbers)

In [43]:
unique_numbers

array([202.,  29.,   1., 130., 204.,   2.,   0.])

In [44]:
new_array = np.resize(unique_numbers, (3, 2))

In [45]:
unique_numbers

array([202.,  29.,   1., 130., 204.,   2.,   0.])

In [46]:
new_array[0][0] = 6

In [47]:
unique_numbers

array([202.,  29.,   1., 130., 204.,   2.,   0.])

In [48]:
new_unique_num = np.resize(unique_numbers, (2,3))

In [49]:
new_unique_num

array([[202.,  29.,   1.],
       [130., 204.,   2.]])

In [50]:
unique_numbers

array([202.,  29.,   1., 130., 204.,   2.,   0.])

#### Assignment

1. Count male and female counts
2. counts
3. sort
4. where
5. linear algebra