In [104]:
from csv import reader
import numpy as np

In [105]:
with open('heart-disease.csv', 'r', encoding='UTF-8') as file:
    data = reader(file)
    data = list(data)

In [106]:
data = np.array(data)

In [107]:
data

array([['\ufeffage', 'sex', 'cp', ..., 'ca', 'thal', 'target'],
       ['63', '1', '3', ..., '0', '1', '1'],
       ['37', '1', '2', ..., '0', '2', '1'],
       ...,
       ['68', '1', '0', ..., '2', '3', '0'],
       ['57', '1', '0', ..., '1', '3', '0'],
       ['57', '0', '1', ..., '1', '2', '0']], dtype='<U8')

In [108]:
header = data[0]
np_data = data[1:,:].astype('float')
np_data

array([[63.,  1.,  3., ...,  0.,  1.,  1.],
       [37.,  1.,  2., ...,  0.,  2.,  1.],
       [41.,  0.,  1., ...,  0.,  2.,  1.],
       ...,
       [68.,  1.,  0., ...,  2.,  3.,  0.],
       [57.,  1.,  0., ...,  1.,  3.,  0.],
       [57.,  0.,  1., ...,  1.,  2.,  0.]])

#### Assignment

1. Count male and female counts
2. counts
3. sort
4. where
5. linear algebra

### Counting Male and Female

In [109]:
sex = data[1:,1].astype('int')

In [110]:
sex

array([1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,

In [111]:
values,counts = np.unique(sex,return_counts=True)

In [112]:
# Male and female counts displayed
for i,j in zip(values,counts):
    print(i,j)

0 96
1 207


### Sorting values by age

In [113]:
data

array([['\ufeffage', 'sex', 'cp', ..., 'ca', 'thal', 'target'],
       ['63', '1', '3', ..., '0', '1', '1'],
       ['37', '1', '2', ..., '0', '2', '1'],
       ...,
       ['68', '1', '0', ..., '2', '3', '0'],
       ['57', '1', '0', ..., '1', '3', '0'],
       ['57', '0', '1', ..., '1', '2', '0']], dtype='<U8')

In [114]:
# Sorted by age as age is in first column
sorted_data = np.sort(np_data,axis=0)

In [115]:
print(sorted_data)

[[29.  0.  0. ...  0.  0.  0.]
 [34.  0.  0. ...  0.  0.  0.]
 [34.  0.  0. ...  0.  1.  0.]
 ...
 [74.  1.  3. ...  4.  3.  1.]
 [76.  1.  3. ...  4.  3.  1.]
 [77.  1.  3. ...  4.  3.  1.]]


In [116]:
# Verify
sorted_data[:,0]

array([29., 34., 34., 35., 35., 35., 35., 37., 37., 38., 38., 38., 39.,
       39., 39., 39., 40., 40., 40., 41., 41., 41., 41., 41., 41., 41.,
       41., 41., 41., 42., 42., 42., 42., 42., 42., 42., 42., 43., 43.,
       43., 43., 43., 43., 43., 43., 44., 44., 44., 44., 44., 44., 44.,
       44., 44., 44., 44., 45., 45., 45., 45., 45., 45., 45., 45., 46.,
       46., 46., 46., 46., 46., 46., 47., 47., 47., 47., 47., 48., 48.,
       48., 48., 48., 48., 48., 49., 49., 49., 49., 49., 50., 50., 50.,
       50., 50., 50., 50., 51., 51., 51., 51., 51., 51., 51., 51., 51.,
       51., 51., 51., 52., 52., 52., 52., 52., 52., 52., 52., 52., 52.,
       52., 52., 52., 53., 53., 53., 53., 53., 53., 53., 53., 54., 54.,
       54., 54., 54., 54., 54., 54., 54., 54., 54., 54., 54., 54., 54.,
       54., 55., 55., 55., 55., 55., 55., 55., 55., 56., 56., 56., 56.,
       56., 56., 56., 56., 56., 56., 56., 57., 57., 57., 57., 57., 57.,
       57., 57., 57., 57., 57., 57., 57., 57., 57., 57., 57., 58

### Using np.where to view index where age <35

In [117]:
sorted_data[np.where(sorted_data[:,0]<35)]

array([[ 29.,   0.,   0.,  94., 126.,   0.,   0.,  71.,   0.,   0.,   0.,
          0.,   0.,   0.],
       [ 34.,   0.,   0.,  94., 131.,   0.,   0.,  88.,   0.,   0.,   0.,
          0.,   0.,   0.],
       [ 34.,   0.,   0., 100., 141.,   0.,   0.,  90.,   0.,   0.,   0.,
          0.,   1.,   0.]])

### Linear Algebra

In [118]:
# dot function
array1 = np.array([1, 3, 5])
array2 = np.array([2, 4, 6])


In [119]:
np.dot(array1, array2)

44

In [120]:
array1 = np.array([[1, 3], 
                   [5, 7]])
array2 = np.array([[2, 4], 
                   [6, 8]])


In [121]:
np.inner(array1, array2)

array([[14, 30],
       [38, 86]])

In [122]:
np.outer(array1,array2)

array([[ 2,  4,  6,  8],
       [ 6, 12, 18, 24],
       [10, 20, 30, 40],
       [14, 28, 42, 56]])

In [123]:
# for deteminant

np.linalg.det(array1)

-7.999999999999998

In [124]:
# TO solve linear eqns
# ax+by = c
# for 2x+4y=5 and 6x+8y = 6

A = np.array([[2,4],
              [6,8]])
B = np.array([5,6])

np.linalg.solve(A,B)

array([-2.  ,  2.25])

In [129]:
# To inverse a matrix
array1 = np.array([[2,4],
                   [6,2]])
if np.linalg.det(array1) == 0:
    print("Sorry Inverse Doesn't exist")
else:
    print(np.linalg.inv(array1))

[[-0.1  0.2]
 [ 0.3 -0.1]]


In [130]:
np.linalg.eig(array1)

(array([ 6.89897949, -2.89897949]),
 array([[ 0.63245553, -0.63245553],
        [ 0.77459667,  0.77459667]]))

In [132]:
np.linalg.matrix_rank(array1)

2

In [133]:
np.linalg.svd(array1)

(array([[-0.52573111, -0.85065081],
        [-0.85065081,  0.52573111]]),
 array([7.23606798, 2.76393202]),
 array([[-0.85065081, -0.52573111],
        [ 0.52573111, -0.85065081]]))