## Objectives

Learn Basics of Numpy Introduction to Numpy

- 1D array
  - zeros(), ones()
  - linspace(), arange(), .array(),
  - random.randint(), random.normal(),
  - random.uniform()
  - indexing, Slicing
  - .any() vs all()
  - broadcasting
- 2D array
  - Introduction
  - reshape()
  - flatten() vs ravel()
  - indexing and slicing
  - axis = 1 vs axis = 0
  - dot product
- cross product
- linalg module
- 3D array and images

- N dimensional Array


In [1]:
import numpy as np

In [16]:
# This increases the dimension of a numpy array
a = np.arange(6)
a2 = a[:,np.newaxis,]
a2

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [38]:
# pythonlist and numpy array

"""
- numpy array is homogeneous else computations would be extremely inefficient
- Faster and more compact than lists
- consumes less memory
rank: number of dimensions
"""

'\n- numpy array is homogeneous else computations would be extremely inefficient\n- Faster and more compact than lists\n- consumes less memory\nrank: number of dimensions\n'

### Creating a basisc array
- np.array()
- zeros()
- ones()
- empty()
- linspace(),
- arange()

a = np.array([1,2,3,4,5])

In [44]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
# also there is empty array
# initially assigned random values
# more fast than zeros just fill every element afterwards
np.empty((2,2))

array([[2.76840208e-316, 0.00000000e+000],
       [2.78331605e-316, 2.59551023e-316]])

In [56]:
np.arange(4)
# array([0, 1, 2, 3])
np.arange(2,9,3) #start, end, step

array([2, 5, 8])

In [61]:
# create an array with linearly spaced values
np.linspace(0,10,num=11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [64]:
# default data type is np.float64 
# We can always specify which datatype we will be using by dtype 
np.ones(2,dtype=np.int64)

array([1, 1])

#### Adding, removing and sorting elements
* np.sort()
* np.concatenate()

In [70]:
np.sort(np.array([[3,2,1,5,6,8],[10,4,2,1,6,8]]),axis=0)

array([[ 3,  2,  1,  1,  6,  8],
       [10,  4,  2,  5,  6,  8]])

In [82]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [83]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [92]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5,6],[7,8]])

In [95]:
np.concatenate((x,y),axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [107]:
np.concatenate((x,y),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### Shape and size of an array
- ndim
- size
- shape

In [111]:
a = np.array([[1, 2, 3], [3, 4, 3], [4, 6, 3]])
a

array([[1, 2, 3],
       [3, 4, 3],
       [4, 6, 3]])

In [112]:
a.ndim

2

In [113]:
a.size

9

In [114]:
a.shape

(3, 3)

#### Reshaping Arrays

In [115]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [116]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [118]:
np.reshape(a,newshape=(3,2),order='F') #order='C' for row major 'F'=Fortran for column major

array([[0, 3],
       [1, 4],
       [2, 5]])

### Adding a new axis to an array

- np.newaxis
- np.expand_dims

In [119]:
# np.newaxis will increase dimensions by one when used once

In [122]:
a  = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [128]:
a[np.newaxis,:].shape

(1, 8)

In [129]:
# for row vector
a[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [132]:
np.expand_dims(a,axis=0) #axis = 0 to add a row @axis=1to add column

array([[0, 1, 2, 3, 4, 5, 6, 7]])

#### Indexing and Slicing

In [133]:
data = np.array([1,2,3,4,5])

In [140]:
data[-2]

4

In [143]:
## Select values
data[data<=3]

array([1, 2, 3])

In [144]:
data[data%2==0]

array([2, 4])

In [146]:
(data>2)

array([False, False,  True,  True,  True])

In [148]:
a[(a>2)&(a%2==0)]

array([4, 6])

In [154]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [157]:
b = np.nonzero(a<5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [158]:
a[b]

array([1, 2, 3, 4])

In [160]:
not_there = np.nonzero(a == 42)
not_there

(array([], dtype=int64), array([], dtype=int64))

#### Create an array from existing data

- slicing
- indexing
- np.hstack()
- np.vstack()
- np.hsplit()
- .view()
- copy()

In [163]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

In [164]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [165]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [172]:
x = np.arange(12).reshape(2,6)
np.hsplit(x,3)

[array([[0, 1],
        [6, 7]]),
 array([[2, 3],
        [8, 9]]),
 array([[ 4,  5],
        [10, 11]])]

In [174]:
# normally view is created while indexing and slicing so the modifications made in new var will also be in the original one
# Which is why we can use .copy() method to make ta copy 
b = a.copy()
b


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Basic Array Operations
- addition
- substraction 
- multiplication
- division

In [178]:
data = np.array([1,2])
ones = np.ones(2,dtype=int)
data

array([1, 2])

In [179]:
data+ones

array([2, 3])

In [176]:
data-ones

array([1, 2])

In [180]:
data*ones

array([1, 2])

In [181]:
data/ones

array([1., 2.])

In [183]:
a = np.arange(9)

In [185]:
a.sum()

36

In [187]:
a = a.reshape(3,3)

In [188]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [191]:
a.sum(axis=0)

array([ 9, 12, 15])

#### Broadcasting

- carry out an operation between an array and a single number
- Operation between vector and scalar
- between 2 different sizes


In [192]:
data = np.array([1,3,8])
data*2

array([ 2,  6, 16])

In [195]:
data.max()
data.min()
data.sum()

12

In [206]:
a = np.array([0.0,10.0,20.0,30.0])
b = np.array([1.0,2.0,3.0])
a[:,np.newaxis]+b


array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [205]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])